name: projects

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: mintblocks/projects
          ref: develop
          path: projects-src

      - name: install deps
        working-directory: projects-src
        run: npm ci

      - name: build static files
        working-directory: projects-src
        run: npm run build
        env:
          NODE_ENV: production
          ROOT: /projects/

      - name: run
        run: |
          npx pm2 delete webpage || true
          npx pm2 start npx --name "webpage" -- serve projects/build -p 4321 --single